"use client";

import { motion } from "framer-motion";
import { Download, Share2 } from "lucide-react";
import type { GeneratedPlan } from "@/store/useTripStore";
import type { TravelStyle } from "@/store/useTripStore";

interface Props {
    plan: GeneratedPlan | null;
    days: number;
    travelers: number;
    travelStyle: TravelStyle;
    preferences: string[];
}

function buildPrintHTML(props: Props): string {
    const { plan, days, travelers, travelStyle, preferences } = props;
    if (!plan) return "";
    const top = plan.rankedDestinations[0];
    if (!top) return "";

    const { stay, travel, food, activities } = top.dailyBudgetBreakdown;

    return `
<!DOCTYPE html>
<html>
<head>
  <title>OttaMind Trip Plan — ${top.name}</title>
  <style>
    body { font-family: 'Segoe UI', system-ui, sans-serif; max-width: 700px; margin: 2rem auto; color: #1a1a2e; }
    h1 { color: #6366f1; }
    .meta { color: #666; margin-bottom: 1.5rem; }
    table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
    th, td { padding: 0.5rem 1rem; text-align: left; border-bottom: 1px solid #eee; }
    th { background: #f8f8ff; }
    .footer { margin-top: 2rem; font-size: 0.8rem; color: #999; }
  </style>
</head>
<body>
  <h1>🗺️ OttaMind Trip Plan</h1>
  <p class="meta">${days} days · ${travelers} travelers · ${travelStyle} style</p>

  <h2>🏆 Top Destination: ${top.name}</h2>
  <p>Score: ${top.score} pts</p>

  <h3>Daily Budget Breakdown</h3>
  <table>
    <tr><th>Category</th><th>Amount (₹)</th></tr>
    <tr><td>Stay</td><td>₹${stay.toLocaleString("en-IN")}</td></tr>
    <tr><td>Travel</td><td>₹${travel.toLocaleString("en-IN")}</td></tr>
    <tr><td>Food</td><td>₹${food.toLocaleString("en-IN")}</td></tr>
    <tr><td>Activities</td><td>₹${activities.toLocaleString("en-IN")}</td></tr>
    <tr><th>Total / Day</th><th>₹${(stay + travel + food + activities).toLocaleString("en-IN")}</th></tr>
  </table>

  <h3>Trip Summary</h3>
  <table>
    <tr><td>Total Budget</td><td>₹${plan.totalBudget.toLocaleString("en-IN")}</td></tr>
    <tr><td>Budget Per Day</td><td>₹${plan.budgetPerDay.toLocaleString("en-IN")}</td></tr>
    <tr><td>Preferences</td><td>${preferences.length ? preferences.join(", ") : "None"}</td></tr>
  </table>

  ${plan.rankedDestinations.length > 1 ? `
  <h3>Alternatives</h3>
  <ul>${plan.rankedDestinations.slice(1).map((d) => `<li>${d.name} (${d.score} pts)</li>`).join("")}</ul>
  ` : ""}

  <p class="footer">Generated by OttaMind · ${new Date().toLocaleDateString()}</p>
</body>
</html>`;
}

function buildShareJSON(props: Props): string {
    const { plan, days, travelers, travelStyle, preferences } = props;
    if (!plan) return "{}";

    return JSON.stringify(
        {
            app: "OttaMind",
            generatedAt: new Date().toISOString(),
            trip: {
                days,
                travelers,
                travelStyle,
                preferences,
                totalBudget: plan.totalBudget,
                budgetPerDay: plan.budgetPerDay,
            },
            destinations: plan.rankedDestinations.map((d) => ({
                name: d.name,
                score: d.score,
                dailyCost: d.dailyBudgetBreakdown,
            })),
        },
        null,
        2,
    );
}

export default function SaveTrip(props: Props) {
    const { plan } = props;
    if (!plan || plan.rankedDestinations.length === 0) return null;

    const handlePrint = () => {
        const html = buildPrintHTML(props);
        const w = window.open("", "_blank");
        if (w) {
            w.document.write(html);
            w.document.close();
            w.print();
        }
    };

    const handleShare = () => {
        const json = buildShareJSON(props);
        const blob = new Blob([json], { type: "application/json" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `ottamind-trip-${Date.now()}.json`;
        a.click();
        URL.revokeObjectURL(url);
    };

    return (
        <motion.div
            className="save-trip-bar"
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4, delay: 0.3 }}
        >
            <button className="save-btn btn-pulse" onClick={handlePrint}>
                <Download size={16} /> Export & Print
            </button>
            <button className="save-btn btn-pulse" onClick={handleShare}>
                <Share2 size={16} /> Share JSON
            </button>
        </motion.div>
    );
}
